#!/bin/bash

# This file is part of The RetroEvolved Project
#
# The RetroEvolved Project is the legal property of its developers, whose names are
# too numerous to list here. Please refer to the COPYRIGHT.md file distributed with this source.
#
# See the LICENSE.md file at the top-level directory of this distribution and
# at https://raw.githubusercontent.com/RetroEvolved/RetroEvolved-Setup/master/LICENSE.md
#

## config / defaults
user="USERTOBECHOSEN"

home="$(eval echo ~$user)"
retroevolved_path="$home/RetroEvolved"

usb_path="$UM_MOUNTPOINT/retroevolved-mount"

## internals
hook_name=${0##*/}

## functions
function log() {
    logger -p user.$1 -t usbmount-"$hook_name"-[$$] -- "$2"
}

function log_cmd() {
    local ret
    local error
    error="$("$@" 2>&1 >/dev/null)"
    ret=$?
    [[ "$ret" -ne 0 ]] && log err "$* - returned $ret - $error"
}

## some sanity checking
if [[ -z "$UM_MOUNTPOINT" ]]; then
    log err "UM_MOUNTPOINT not set!"
    exit 0
fi

if [[ ! -d "$UM_MOUNTPOINT" ]]; then
    log err "UM_MOUNTPOINT is not a directory"
    exit 0
fi

# check for a retroevolved-mount folder
if [[ ! -d "$usb_path" ]]; then
    exit 0
fi

if [[ -z "$(ls -A "$usb_path")" ]]; then
    log info "Copying existing $retroevolved_path to $usb_path ..."
    log_cmd rsync -rtu "$retroevolved_path/" "$usb_path/"
fi

log info "Mounting $usb_path over $retroevolved_path ..."
log_cmd mount -o bind "$usb_path" "$retroevolved_path"
